<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.104" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.101.4" />
  </ItemGroup>

</Project>
